# Dockerfile used for creating a container capable to run AcmeAir monolithic
# Must be running on the same network as the mongodb container
#FROM icr.io/appcafe/open-liberty:beta-instanton
FROM open-liberty:myjdk-openj9

COPY --chown=1001:0 LibertyFiles/server.xml /config/server.xml
COPY --chown=1001:0 LibertyFiles/acmeair-java-2.0.0-SNAPSHOT.war /config/apps/
EXPOSE 9080

#USER root
#ENV OPENJ9_SCC=false
ENV VERBOSE=true
#RUN features.sh
RUN configure.sh
ENV OPENJ9_JAVA_OPTIONS="-Xjit:verbose={codecache,compilePerformance},vlog=vlog.txt,count=1,disableCodeCacheConsolidation,safeReservePhysicalMemoryValue=10240 -Xcodecache512K"
#RUN mkdir /cores; \
#    chmod 775 /cores;\
